name = "url-shortener"
main = "dist/index.js"

compatibility_date = "2024-05-01"
workers_dev = true

kv_namespaces = [
  { binding = "URL_KV", id = "a5ddf19feeec451ba7faada50fcf98bb" }
]

[placement]
mode = "smart"

[build]
command = "bun run build"
