name = "url-shortener"
main = "dist/index.js"

compatibility_date = "2024-05-01"
workers_dev = true

kv_namespaces = [
  { binding = "URL_KV", id = "f616403dc9ab4500aeaa6439183b624f" }
]

[placement]
mode = "smart"

[build]
command = "bun run build"
